namespace Energy.Domain.Models;

public record RenewableEnergyProject(
    int Id,
    string? OldRefId,
    int RefId,
    DateTime? RecordLastUpdated,
    string? Operator,
    string? SiteName,
    TechnologyType? TechnologyType,
    string? StorageType,
    string? StorageCoLocationRepdRefId,
    decimal? InstalledCapacityMWe,
    string? ShareCommunityScheme,
    bool ChpEnabled,
    string? CfdAllocationRound,
    decimal? RoBandingRocPerMWh,
    decimal? FitTariffPencePerKWh,
    decimal? CfdCapacityMW,
    decimal? TurbineCapacityMW,
    int? NumberOfTurbines,
    decimal? HeightOfTurbinesMetres,
    string? MountingTypeForSolar,
    string? DevelopmentStatus,
    string? DevelopmentStatusShort,
    string? ReApplyingNewRepdRef,
    string? ReApplyingOldRepdRef,
    string? Address,
    string? County,
    string? Region,
    string? Country,
    string? PostCode,
    decimal? XCoordinate,
    decimal? YCoordinate,
    string? PlanningAuthority,
    string? PlanningApplicationReference,
    string? AppealReference,
    string? SecretaryOfStateReference,
    string? TypeOfSecretaryOfStateIntervention,
    string? JudicialReview,
    string? OffshoreWindRound,
    DateTime? PlanningApplicationSubmitted,
    DateTime? PlanningApplicationWithdrawn,
    DateTime? PlanningPermissionRefused,
    DateTime? AppealLodged,
    DateTime? AppealWithdrawn,
    DateTime? AppealRefused,
    DateTime? AppealGranted,
    DateTime? PlanningPermissionGranted,
    DateTime? SecretaryOfStateIntervened,
    DateTime? SecretaryOfStateRefusal,
    DateTime? SecretaryOfStateGranted,
    DateTime? PlanningPermissionExpired,
    DateTime? UnderConstruction,
    DateTime? Operational,
    string? HeatNetworkRef,
    decimal? SolarSiteAreaSqm)
{
    public RenewableEnergyProject() : this(
        0, null, 0, null, null, null, null, null,
        null, null, null, false, null, null, null, null,
        null, null, null, null, null, null, null, null,
        null, null, null, null, null, null, null, null,
        null, null, null, null, null, null, null, null,
        null, null, null, null, null, null, null, null,
        null, null, null, null, null, null) { }
}
