// <auto-generated />
using System;
using Energy.Infrastructure.AzureSqlRepository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Energy.Infrastructure.AzureSqlRepository.Migrations
{
    [DbContext(typeof(EnergyDbContext))]
    [Migration("20260325153015_ChangeCoordinatesToDecimal")]
    partial class ChangeCoordinatesToDecimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Energy.Infrastructure.AzureSqlRepository.Models.RenewableEnergyProjectDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AppealGranted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AppealLodged")
                        .HasColumnType("datetime2");

                    b.Property<string>("AppealReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AppealRefused")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AppealWithdrawn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CfdAllocationRound")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CfdCapacityMW")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("ChpEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevelopmentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevelopmentStatusShort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FitTariffPencePerKWh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("HeatNetworkRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HeightOfTurbinesMetres")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InstalledCapacityMWe")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("JudicialReview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MountingTypeForSolar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfTurbines")
                        .HasColumnType("int");

                    b.Property<string>("OffshoreWindRound")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldRefId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Operational")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanningApplicationReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PlanningApplicationSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlanningApplicationWithdrawn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanningAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PlanningPermissionExpired")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlanningPermissionGranted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlanningPermissionRefused")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReApplyingNewRepdRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReApplyingOldRepdRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RecordLastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("RefId")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RoBandingRocPerMWh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("SecretaryOfStateGranted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SecretaryOfStateIntervened")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecretaryOfStateReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SecretaryOfStateRefusal")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShareCommunityScheme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SolarSiteAreaSqm")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("StorageCoLocationRepdRefId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnologyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TurbineCapacityMW")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TypeOfSecretaryOfStateIntervention")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UnderConstruction")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("XCoordinate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("YCoordinate")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("RefId")
                        .IsUnique();

                    b.ToTable("RenewableEnergyProjects", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
