using Energy.Domain.Models;
using Energy.Infrastructure.AzureSqlRepository.Models;

namespace Energy.Infrastructure.AzureSqlRepository.Mapping;

public static class RenewableEnergyProjectMappingExtensions
{
    public static RenewableEnergyProject ToDomain(this RenewableEnergyProjectDb db) => new(
        Id: db.Id,
        OldRefId: db.OldRefId,
        RefId: db.RefId,
        RecordLastUpdated: db.RecordLastUpdated,
        Operator: db.Operator,
        SiteName: db.SiteName,
        TechnologyType: db.TechnologyType,
        StorageType: db.StorageType,
        StorageCoLocationRepdRefId: db.StorageCoLocationRepdRefId,
        InstalledCapacityMWe: db.InstalledCapacityMWe,
        ShareCommunityScheme: db.ShareCommunityScheme,
        ChpEnabled: db.ChpEnabled,
        CfdAllocationRound: db.CfdAllocationRound,
        RoBandingRocPerMWh: db.RoBandingRocPerMWh,
        FitTariffPencePerKWh: db.FitTariffPencePerKWh,
        CfdCapacityMW: db.CfdCapacityMW,
        TurbineCapacityMW: db.TurbineCapacityMW,
        NumberOfTurbines: db.NumberOfTurbines,
        HeightOfTurbinesMetres: db.HeightOfTurbinesMetres,
        MountingTypeForSolar: db.MountingTypeForSolar,
        DevelopmentStatus: db.DevelopmentStatus,
        DevelopmentStatusShort: db.DevelopmentStatusShort,
        ReApplyingNewRepdRef: db.ReApplyingNewRepdRef,
        ReApplyingOldRepdRef: db.ReApplyingOldRepdRef,
        Address: db.Address,
        County: db.County,
        Region: db.Region,
        Country: db.Country,
        PostCode: db.PostCode,
        XCoordinate: db.XCoordinate,
        YCoordinate: db.YCoordinate,
        PlanningAuthority: db.PlanningAuthority,
        PlanningApplicationReference: db.PlanningApplicationReference,
        AppealReference: db.AppealReference,
        SecretaryOfStateReference: db.SecretaryOfStateReference,
        TypeOfSecretaryOfStateIntervention: db.TypeOfSecretaryOfStateIntervention,
        JudicialReview: db.JudicialReview,
        OffshoreWindRound: db.OffshoreWindRound,
        PlanningApplicationSubmitted: db.PlanningApplicationSubmitted,
        PlanningApplicationWithdrawn: db.PlanningApplicationWithdrawn,
        PlanningPermissionRefused: db.PlanningPermissionRefused,
        AppealLodged: db.AppealLodged,
        AppealWithdrawn: db.AppealWithdrawn,
        AppealRefused: db.AppealRefused,
        AppealGranted: db.AppealGranted,
        PlanningPermissionGranted: db.PlanningPermissionGranted,
        SecretaryOfStateIntervened: db.SecretaryOfStateIntervened,
        SecretaryOfStateRefusal: db.SecretaryOfStateRefusal,
        SecretaryOfStateGranted: db.SecretaryOfStateGranted,
        PlanningPermissionExpired: db.PlanningPermissionExpired,
        UnderConstruction: db.UnderConstruction,
        Operational: db.Operational,
        HeatNetworkRef: db.HeatNetworkRef,
        SolarSiteAreaSqm: db.SolarSiteAreaSqm);

    public static RenewableEnergyProjectDb FromDomain(this RenewableEnergyProject domain) => new()
    {
        OldRefId = domain.OldRefId,
        RefId = domain.RefId,
        RecordLastUpdated = domain.RecordLastUpdated,
        Operator = domain.Operator,
        SiteName = domain.SiteName,
        TechnologyType = domain.TechnologyType,
        StorageType = domain.StorageType,
        StorageCoLocationRepdRefId = domain.StorageCoLocationRepdRefId,
        InstalledCapacityMWe = domain.InstalledCapacityMWe,
        ShareCommunityScheme = domain.ShareCommunityScheme,
        ChpEnabled = domain.ChpEnabled,
        CfdAllocationRound = domain.CfdAllocationRound,
        RoBandingRocPerMWh = domain.RoBandingRocPerMWh,
        FitTariffPencePerKWh = domain.FitTariffPencePerKWh,
        CfdCapacityMW = domain.CfdCapacityMW,
        TurbineCapacityMW = domain.TurbineCapacityMW,
        NumberOfTurbines = domain.NumberOfTurbines,
        HeightOfTurbinesMetres = domain.HeightOfTurbinesMetres,
        MountingTypeForSolar = domain.MountingTypeForSolar,
        DevelopmentStatus = domain.DevelopmentStatus,
        DevelopmentStatusShort = domain.DevelopmentStatusShort,
        ReApplyingNewRepdRef = domain.ReApplyingNewRepdRef,
        ReApplyingOldRepdRef = domain.ReApplyingOldRepdRef,
        Address = domain.Address,
        County = domain.County,
        Region = domain.Region,
        Country = domain.Country,
        PostCode = domain.PostCode,
        XCoordinate = domain.XCoordinate,
        YCoordinate = domain.YCoordinate,
        PlanningAuthority = domain.PlanningAuthority,
        PlanningApplicationReference = domain.PlanningApplicationReference,
        AppealReference = domain.AppealReference,
        SecretaryOfStateReference = domain.SecretaryOfStateReference,
        TypeOfSecretaryOfStateIntervention = domain.TypeOfSecretaryOfStateIntervention,
        JudicialReview = domain.JudicialReview,
        OffshoreWindRound = domain.OffshoreWindRound,
        PlanningApplicationSubmitted = domain.PlanningApplicationSubmitted,
        PlanningApplicationWithdrawn = domain.PlanningApplicationWithdrawn,
        PlanningPermissionRefused = domain.PlanningPermissionRefused,
        AppealLodged = domain.AppealLodged,
        AppealWithdrawn = domain.AppealWithdrawn,
        AppealRefused = domain.AppealRefused,
        AppealGranted = domain.AppealGranted,
        PlanningPermissionGranted = domain.PlanningPermissionGranted,
        SecretaryOfStateIntervened = domain.SecretaryOfStateIntervened,
        SecretaryOfStateRefusal = domain.SecretaryOfStateRefusal,
        SecretaryOfStateGranted = domain.SecretaryOfStateGranted,
        PlanningPermissionExpired = domain.PlanningPermissionExpired,
        UnderConstruction = domain.UnderConstruction,
        Operational = domain.Operational,
        HeatNetworkRef = domain.HeatNetworkRef,
        SolarSiteAreaSqm = domain.SolarSiteAreaSqm
    };
}
